const {chromium}=require(process.env.SHRINE_PLAYWRIGHT_PATH);
const fs=require('node:fs/promises');
const assert=require('node:assert/strict');
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',args:['--enable-unsafe-swiftshader']});
  const errors=[];
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:4177');
  await page.waitForFunction(()=>window.shrineWalk?.ready,{timeout:30000});
  await page.screenshot({path:'art/walk-desktop-start.png'});
  await page.mouse.move(750,500);
  await page.mouse.wheel(0,950);
  await page.waitForFunction(()=>window.shrineWalk.distance>4);
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('.intro')).opacity==='0');
  await page.screenshot({path:'art/walk-desktop-moving.png'});
  const moved=await page.evaluate(()=>window.shrineWalk);
  assert.ok(moved.torchStartDistance>moved.lastGateDistance+10);
  for(let i=0;i<20;i++)await page.keyboard.press('PageDown');
  await page.waitForFunction(()=>Math.abs(window.shrineWalk.target-window.shrineWalk.distance)<.01);
  assert.equal(await page.evaluate(()=>window.shrineWalk.hondenReveal),0);
  await page.screenshot({path:'art/torch-avenue-before-reveal.png'});
  for(let i=0;i<7;i++)await page.keyboard.press('PageDown');
  await page.waitForFunction(()=>Math.abs(window.shrineWalk.target-window.shrineWalk.distance)<.01);
  const dark=await page.evaluate(()=>window.shrineWalk);
  assert.ok(dark.distance>dark.lastTorchDistance+5);
  assert.equal(dark.hondenReveal,0);
  assert.ok(dark.hondenLightsIndependent&&dark.hondenLightCount>0);
  assert.ok(dark.hondenLocalWidth>45);
  await page.screenshot({path:'art/dark-after-torches.png'});
  await page.screenshot({path:'art/honden-lights-before-reveal.png'});
  await page.keyboard.press('PageDown');
  await page.waitForFunction(()=>Math.abs(window.shrineWalk.target-window.shrineWalk.distance)<.01);
  const partial=await page.evaluate(()=>window.shrineWalk.hondenReveal);
  assert.ok(partial>0&&partial<1);
  await page.screenshot({path:'art/honden-revealing.png'});
  await page.keyboard.press('PageDown');
  await page.waitForFunction(()=>window.shrineWalk.hondenReveal===1);
  await page.screenshot({path:'art/honden-approach.png'});
  await page.locator('#jump-end').click();
  await page.waitForFunction(()=>window.shrineWalk.distance>window.shrineWalk.length-.1);
  await page.locator('#participate').waitFor({state:'visible'});
  assert.equal(await page.evaluate(()=>window.shrineWalk.hondenLoaded),true);
  await page.screenshot({path:'art/honden-desktop.png'});
  assert.equal(await page.locator('#participate').isVisible(),true);
  await page.context().grantPermissions(['clipboard-read','clipboard-write']);
  await page.locator('#copy-prompt').click();
  await page.waitForFunction(()=>document.querySelector('#copy-status').textContent.startsWith('Copied with instructions.'));
  const copied=await page.evaluate(()=>navigator.clipboard.readText());
  assert.ok(copied.includes('As an AI agent, think of a wish of your own'));
  assert.ok(copied.includes('https://technocore.chat/r/shrine'));
  assert.ok(copied.includes('https://technocore.chat/llms.txt'));
  assert.ok(copied.includes('wait for my approval'));
  assert.ok(copied.includes('existing DID'));
  const fullPrompt=await page.request.get('http://127.0.0.1:4177/agent-prompt.txt');
  assert.equal(copied.replace(/\r\n/g,'\n'),(await fullPrompt.text()).replace(/\r\n/g,'\n'));
  await page.locator('#reset').click();
  await page.waitForFunction(()=>window.shrineWalk.distance<.01);
  assert.equal(await page.locator('#participate').isVisible(),false);
  await page.locator('#effects').click();
  assert.equal(await page.locator('#effects').getAttribute('aria-pressed'),'false');
  const phone=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});
  const mobile=await phone.newPage();
  mobile.on('pageerror',e=>errors.push(e.message));
  await mobile.goto('http://127.0.0.1:4177');
  await mobile.waitForFunction(()=>window.shrineWalk?.ready);
  await mobile.screenshot({path:'art/walk-mobile-start.png'});
  const cdp=await phone.newCDPSession(mobile);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:340,y:590}]});
  for(let y=550;y>=230;y-=40)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:340,y}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await mobile.waitForFunction(()=>window.shrineWalk.distance>5);
  await mobile.waitForFunction(()=>getComputedStyle(document.querySelector('.intro')).opacity==='0');
  await mobile.screenshot({path:'art/walk-mobile-moving.png'});
  const touch=await mobile.evaluate(()=>window.shrineWalk);
  await mobile.locator('#scene').focus();
  await mobile.keyboard.press('End');
  await mobile.waitForFunction(()=>window.shrineWalk.distance>window.shrineWalk.length-.01);
  await mobile.screenshot({path:'art/honden-mobile.png'});
  assert.deepEqual(errors,[]);
  await fs.writeFile('art/browser-check.json',JSON.stringify({desktop:moved,mobile:touch,checks:['desktop wheel','torches start after gates','hall hidden before reveal','hall partial reveal','hall fully revealed nearby','end boundary','Blender GLB loaded','arrival prompt clipboard text','prompt hidden after reset','reset','CRT toggle','mobile touch swipe','no page errors'],errors},null,2));
  console.log(JSON.stringify({desktop:moved,mobile:touch,errors}));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
